-- 菜单
CREATE TABLE t_menu_info (
	MI_ID INT NOT NULL,
	MI_CODE VARCHAR(20) NOT NULL,
	MI_ID_PATH VARCHAR(250) NOT NULL,
	MI_IMG_PATH VARCHAR(250) NOT NULL,
	MI_LEVEL SMALLINT NOT NULL,
	MI_NAME VARCHAR(40) NOT NULL,
	MI_NAME_PATH VARCHAR(250) NOT NULL,
	MI_URL VARCHAR(250) NOT NULL,
	MI_PARENT_ID INT,
	PRIMARY KEY (MI_ID)
) ENGINE=InnoDB;

CREATE UNIQUE INDEX MI_CODE ON t_menu_info (MI_CODE ASC);
